Deleting from db
pacman-player/player-core pull request #131
Opened 2020-03-04 08:19 UTC by SandAapps

- устранены исключения при удалении Users, companies, если у них есть связи с другими сущностями и таблицами в БД
- при удалении типа компании, если в ошибке содержится тип DataIntegrityViolationException, означающее существование зависимых таблиц, выводится соответствующее оповещение о невозможности удалить тип. Удалить его можно только при отсутствии связи с компаниями.

2020-03-04 14:15 UTC, revseev requested changes
См. комменты по коду + после мерджа с https://github.com/pacman-player/player-core/pull/115
не получается удалить юзеров/админов, ошибка сервера 500.

2020-03-04 14:15 UTC, revseev commented on src/main/resources/static/js/admin/establishments.js
> +                let cautation = "Вы не можете удалить данный тип заведения, т.к. к нему относятся одна или несколько компаний";
Опечатка, переименовать в cautionMessage (например)

2020-03-04 14:15 UTC, revseev commented on src/main/java/spring/app/model/Company.java
> +        this.orderSongs = orderSongs;
убрать закомментированные блоки, либо добавить описание почему они могут понадобиться тут другим разработчикам.

2020-03-04 14:15 UTC, revseev commented on src/main/java/spring/app/dao/impl/OrderSongDaoImpl.java
> +                .setParameter("id", id).getSingleResult();
Зачем? было читабельнее. 
.getSingleResult(); перенести на новую строку

2020-03-04 14:15 UTC, revseev commented on src/main/java/spring/app/dao/impl/NotificationDaoImpl.java
> +    }
А нельзя сразу удалить за один запрос к базе?

2020-03-04 14:15 UTC, revseev commented on src/main/resources/static/js/admin/establishments.js
>          }
В это строке синтаксическая ошибка Uncaught SyntaxError: missing ) after argument list
Не загружаются типы заведений

2020-03-04 14:15 UTC, revseev commented on src/main/java/spring/app/dao/impl/OrderSongDaoImpl.java
> +    }
а нельзя указать результирующий класс вторым параметром в методе createNativeQuery? Если иначе упростить нельзя, снабдить комментарием для чего происходит каст в цикле.

2020-03-05 20:53 UTC, SandAapps commented
> См. комменты по коду + после мерджа с #115
> не получается удалить юзеров/админов, ошибка сервера 500.

#115 сейчас в деве? я запулила еще раз после мержа сегодняшнего дева. у меня при проверке все удаляются вплоть до админа который вошел в систему.

2020-03-05 21:02 UTC, SandAapps commented on src/main/java/spring/app/dao/impl/NotificationDaoImpl.java
> +    }
а это как? не понимаю вопрос

2020-03-05 21:06 UTC, SandAapps commented on src/main/resources/static/js/admin/establishments.js
> +                let cautation = "Вы не можете удалить данный тип заведения, т.к. к нему относятся одна или несколько компаний";
опечатку убрала

2020-03-05 21:16 UTC, SandAapps commented on src/main/resources/static/js/admin/establishments.js
>          }
куда не загружаются? в какой этой строке? 161?

2020-03-05 21:34 UTC, SandAapps commented on src/main/java/spring/app/dao/impl/OrderSongDaoImpl.java
> +    }
я не знаю можно или нельзя. Но если поставить "результирующий класс" - оно не работает. каст в цикле потому что из query возвращаются Object.

2020-03-06 07:20 UTC, revseev submitted a review, later dismissed

2020-03-06 07:20 UTC, revseev commented on src/main/resources/static/js/admin/establishments.js
>          }
Да, была в 161 строке. Проблемы сейчас нет.

2020-03-06 07:23 UTC, revseev commented on src/main/java/spring/app/dao/impl/NotificationDaoImpl.java
> +    }
У тебя - 1) поиск всех (n записей) по id пользователя. 2) теперь (n запросов к базе) каждую удаляем отдельно в цикле.
Предложение было написать query которое сразу удаляет в базе все записи, удовлетворяющие условию id пользователя

2020-03-06 14:58 UTC, SandAapps commented on src/main/java/spring/app/dao/impl/NotificationDaoImpl.java
> +    }
Пиши пример

2020-03-06 17:27 UTC, SandAapps commented on src/main/java/spring/app/dao/impl/NotificationDaoImpl.java
> +    }
переделано через Delete напрямую в sql без хайбернейт

2020-03-06 18:02 UTC, revseev approved these changes

2020-03-08 12:09 UTC, merged